export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ALLOW_REGISTER = 'ALLOW_REGISTER';
export const UPDATE_TIMELINE = 'UPDATE_TIMELINE';
export const UPDATE_PENDING_KEY = 'UPDATE_PENDING_KEY';
export const UPDATE_FILTER_BY = 'UPDATE_FILTER_BY';

